feat: local run with DB
shuttle-hq/shuttle pull request #196
Opened 2022-05-31 14:30 UTC by chesedo

Adds DB support to local run

For #120

2022-05-31 14:30 UTC, NodarD commented
Task linked: [CU-2cta64h Local runs creates all DB as docker containers](https://app.clickup.com/t/2cta64h)

2022-06-07 10:33 UTC, bmoxb requested changes
Super cool :) One minor problem I've encountered however is when running an example which uses a Postgres database, I get an 'address already in use' error if I have an instance of Postgres already running locally on my computer. Perhaps it would be a good idea to run Postgres on a non-standard port to avoid this?

2022-06-07 10:33 UTC, bmoxb commented on cargo-shuttle/src/factory.rs
> +                    item.id.is_some() && item.id.as_deref().unwrap() == id
I think you can do a direct comparison instead of unwrapping here.

```suggestion
                    item.id.as_deref() == Some(id)
```

2022-06-08 10:16 UTC, bmoxb approved these changes

2022-06-08 12:06 UTC, merged