fix: --name was ignored when not running from cargo folder
shuttle-hq/shuttle pull request #929
Opened 2023-05-21 07:41 UTC by imor

## Description of change

This PR allows users to run cargo shuttle commands from outside a cargo folder when the `--name` option is provided.

closes issue #927 .

## How Has This Been Tested (if applicable)?

Ran the command `cargo shuttle stop --name helloworld` locally. It no longer throws the "could not find Cargo.toml" error.

2023-05-26 23:47 UTC, jonaro00 approved these changes
Works for me 😄

2023-05-26 23:52 UTC, jonaro00 requested changes

2023-05-26 23:52 UTC, jonaro00 commented on cargo-shuttle/src/config.rs
> +        };
```suggestion
        let workspace_path = project_args.workspace_path().unwrap_or(project_args.working_directory.clone());
```

2023-05-27 00:03 UTC, jonaro00 commented
Closes #927

2023-05-28 08:12 UTC, imor commented
Thanks @jonaro00 for suggesting use of `unwrap_or`.

2023-05-30 12:31 UTC, oddgrd approved these changes
Looks good to me, thanks @imor! :heart: And thanks @jonaro00 for the issue and review!

2023-05-30 13:17 UTC, merged